### ISSUE TITLE
Problem building torch-android

### ISSUE THREAD

**Issue by shaile7** [soumith/torch-android#10]
I have installed torch according to http://torch.ch/docs/getting-started.html#_ 
but with mkl (instructions here: https://github.com/torch/dok/blob/master/docinstall/blas.md)
torch is correctly installed. typing 'th' I get

  ______             __   |  Torch7  
 /_  **/**  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ **/ __/ _ \  |  Type ? for help  
 /_/  \_**/_/  __/_//_/  |  https://github.com/torch  
                          |  http://torch.ch                  

th>
(the nice "Torch" script is distorted here due to different character size)

I have installed Java sdk and android sdk and they seem to work.
now to install torch-android I type: 
torch-android-master/$ sudo sh build.sh 
and get the following error

Torch-7 not found on system. Please install it using instructions from http://torch.ch

the directory ~/torch/install/bin is in the PATH and contains:

itorch (program)
itorch_launcher (program)
json2lua (program)
lua2json (program)
luajit (program)
mdcat (program)
qlua (program)
th (program)
luarocks (txt file)
luarocks-admin (txt file)
torch-activate (txt file)

any advice ?

**Comment by culurciello** [comment]
If you are looking for the easiest way to deploy on embedded, or Android or iOs, thnets now contains also an easy stripped-version of openBLAS, so it is really easy to compile it on embedded devices: https://github.com/mvitez/thnets. We highly recommend it

**Comment by soumith** [comment]
should be fixed now
