### ISSUE TITLE
libnn.so is not generated

### ISSUE THREAD

**Issue by jaewoosong** [soumith/torch-android#105]
Good morning!

When I build with `WITH_CUDA=OFF`, `libnn.so` is not generated. Other shared object files are generated without any problem. (The same question was in #71 but it was closed without a solution.)

If anybody knows how to solve the problem, please help me!

**Comment by paramsen** [comment]
@jaewoosong Did you have any success with this matter?

**Comment by jaewoosong** [comment]
@paramsen Good morning. I found that if I use the newest Torch version, then `libnn.so` is not needed. It seems `libnn.so` is included in `libnnx.so`. I don't remember in detail but somehow the problem was solved.
