### ISSUE TITLE
Adding new modules

### ISSUE THREAD

**Issue by vidda13** [soumith/torch-android#11]
I am trying to add cutorch module but I am facing issues in building it. I added the cutorch folder under src/3rdparty and tried building it from the top level directory. Is there a simpler way to add on new modules ?

**Comment by vidda13** [comment]
I get the following issue when i build for cutorch.
 Found CUDA: /usr/local/cuda-7.0 (found suitable version "7.0", minimum required is "5.5") 
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0
CMake Warning (dev) at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:1448 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  3rdparty/cutorch/lib/THC/CMakeLists.txt:102 (CUDA_ADD_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "THC"

**Comment by soumith** [comment]
torch-android cant have CUDA. There's no CUDA support on android.

**Comment by vidda13** [comment]
But I have a TK1 with android flashed on it and was planning to port torch code to the device. How would I use modules like cutorch or cunn on such a device.

**Comment by culurciello** [comment]
If you are looking for the easiest way to deploy on embedded, or Android or iOs, thnets now contains also an easy stripped-version of openBLAS, so it is really easy to compile it on embedded devices: https://github.com/mvitez/thnets. We highly recommend it
