### ISSUE TITLE
Demos failing

### ISSUE THREAD

**Issue by mattpoggi** [soumith/torch-android#12]
Hi,
I successfully built android-torch and I also built android-demo and elab face detector. I installed them on my OnePlus One, but when I tried to run both of them crashed: in particular, the face detector demo closes when I press one of the three starting buttons (start 240p, 480p or 768p).
Anyone experiencing the same issue?

**Comment by borisfom** [comment]
There was a substantia rewrite since then, Please let us know if it works for you now.
