### ISSUE TITLE
problems to load pre trained network in Android

### ISSUE THREAD

**Issue by mijailronald23** [soumith/torch-android#13]
Hi all..

I have some problems with load my pre-trained network in the cellphone. I have this print code from ./adb logcat 

I/Torch-cifar-demo( 5730): load pretrained network file
I/Torch-cifar-demo( 5730): Torch Error doing resource: %s
I/Torch-cifar-demo( 5730): cannot open <cifar.net> in mode r 

It seems than the "cifar.net" cannot open in Android. But when i try to load the same file with torch7, it seems its okay 

th> load=torch.load('cifar.net')
                                                                      [0.0133s] 
th> load
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> output](1): nn.SpatialConvolutionMap
  (2): nn.Tanh
  (3): nn.SpatialMaxPooling(2,2,2,2)
  (4): nn.SpatialConvolutionMap
  (5): nn.Tanh
  (6): nn.SpatialMaxPooling(2,2,2,2)
  (7): nn.Reshape(6400)
  (8): nn.Linear(6400 -> 128)
  (9): nn.Tanh
  (10): nn.Linear(128 -> 10)
  (11): nn.LogSoftMax
}

Otherwise, when i try to load the "cifar.net" from "cifar-demo" example in "toarch-android", it seems doesnt work in torch7 

th> load=torch.load('cifar.net')
/home/mijail/torch/install/share/lua/5.1/torch/File.lua:294: unknown object
stack traceback:
    [C]: in function 'error'
    /home/mijail/torch/install/share/lua/5.1/torch/File.lua:294: in function </home/mijail/torch/install/share/lua/5.1/torch/File.lua:190>
    [C]: in function 'read'
    /home/mijail/torch/install/share/lua/5.1/torch/File.lua:270: in function 'readObject'
    /home/mijail/torch/install/share/lua/5.1/torch/File.lua:288: in function 'readObject'
    /home/mijail/torch/install/share/lua/5.1/torch/File.lua:272: in function 'readObject'
    /home/mijail/torch/install/share/lua/5.1/torch/File.lua:311: in function 'load'
    [string "load=torch.load('cifar.net')"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/mijail/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
    ...jail/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
    [C]: at 0x00406670  

In some moment when you  download your model into the android, Do you change the format? How can i do that? Because in the File - "init.lua" you call the function: 

model=torch.load('cifar.net','r','apk')

How can you change your cifar.net into an Apk file with torch?

**Comment by yonadavs** [comment]
Did you place the file in the project's /assets/ directory?

**Comment by mseyed** [comment]
Here is the problem. I'm not able to load the provided cifar.net model in torch. Similarly I can not load my trained model in torch android. Could you please clarify if you do anything specific to prepare the trained model for android?

Here is what I run to load the pretrained cifar.net:
require 'torch'
require 'nn'
require 'nnx'
require 'dok'
require 'image'
model=torch.load('cifar.net','r','apk')
I get the following error:

...torch/install/share/lua/5.1/torch/File.lua:310: attempt to call a nil value
stack traceback:
    ...torch/install/share/lua/5.1/torch/File.lua:310: in function 'load'
    [string "model=torch.load('cifar.net','r','apk')"]:1: in main chunk
    [C]: in function 'xpcall'
    ...torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
    ...torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
    [C]: at 0x00406670

If I try to load the model using 
model=torch.load('cifar.net')
I get the following error:

...torch/install/share/lua/5.1/torch/File.lua:294: unknown object
stack traceback:
    [C]: in function 'error'
    ...torch/install/share/lua/5.1/torch/File.lua:294: in function <...torch/install/share/lua/5.1/torch/File.lua:190>
    [C]: in function 'read'
    ...torch/install/share/lua/5.1/torch/File.lua:270: in function 'readObject'
    ...torch/install/share/lua/5.1/torch/File.lua:288: in function 'readObject'
    ...torch/install/share/lua/5.1/torch/File.lua:272: in function 'readObject'
    ...torch/install/share/lua/5.1/torch/File.lua:311: in function 'load'
    [string "model=torch.load('cifar.net')"]:1: in main chunk
    [C]: in function 'xpcall'
    ...torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
    ...torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
    [C]: at 0x00406670  

I also tried it with 'ascii' with no success.
It would be great if you can clarify if there is anything else that I should do to load the model.

**Comment by culurciello** [comment]
If you are looking for the easiest way to deploy on embedded, or Android or iOs, thnets now contains also an easy stripped-version of openBLAS, so it is really easy to compile it on embedded devices: https://github.com/mvitez/thnets. We highly recommend it

**Comment by thelinuxmaniac** [comment]
I also encountered similar error messages while trying to load a torch7 neural network file in torch-android:

```
I/torchdemo(14448): Error doing resource: %s
I/torchdemo(14448): cannot open <ep31.net> from apk
D/SurfaceFlinger(  280): FPS : 18.70
W/SurfaceFlinger(  280): Fail to Open /sys/devices/platform/gpusysfs/fps
F/art     (14448): sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf4
F/art     (14448): sart/runtime/check_jni.cc:65]     string: '\F4cannot open <ep31.net> from apk'
F/art     (14448): sart/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (14448): sart/runtime/check_jni.cc:65]     from java.lang.String com.torch.torchdemo.TorchDemo.callTorch(android.content.res.AssetManager)
F/art     (14448): sart/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
F/art     (14448): sart/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x86f5bef0 self=0xb4d07800
F/art     (14448): sart/runtime/check_jni.cc:65]   | sysTid=14448 nice=-11 cgrp=apps sched=0/0 handle=0xb6f05ec8
```

Interestingly, the `torch-android/facedetector_e-lab/assets/face.net.arm` model file cannot be loaded in torch-desktop. So it appears that the network model file has to be converted to some format before it can be used with Android. Does anyone know what conversion should be done?

**Comment by thelinuxmaniac** [comment]
```
char buffer[4096]; // buffer for textview output
buffer[0] = '\0'; // avoids "illegal start byte 0xf4" error ...
```

The `buffer` variable should be initialized to an empty string (with null terminated character) to avoid the following error:

```
F/art     (14448): sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf4
F/art     (14448): sart/runtime/check_jni.cc:65]     string: '\F4cannot open <ep31.net> from apk'
F/art     (14448): sart/runtime/check_jni.cc:65]     in call to NewStringUTF
```

**Comment by soumith** [comment]
I just did a huge refactor and merged it to master.
Now you can do something like:
model = torch.load('cnn_model.net', 'apkbinary64') (apkbinary64 because you saved the model on a 64-bit computer).

Example is here: https://github.com/soumith/torch-android/blob/master/demos/android-demo-cifar/application/assets/init-only.lua#L49
in this case, they are using apkbinary32 because they trained and saved the model on 32-bit computer.

Also, before loading your model, you will likely have to load the packages referenced in the model, so for example you might have to add: 
require 'nn' 

before you do torch.load(...)
