### ISSUE TITLE
Porting cutorch to android

### ISSUE THREAD

**Issue by vidda13** [soumith/torch-android#14]
Hi,

 When I try to port cutorch to android I get the following issue "could not unmap to shared memory file" during run time of the torch demo(android-demo). This issue gets resolved if I change TH_STORAGE_FREEMEM value to 8. However I still get the issue "bad argument #2 (invalid parent class name nn.Module". Would you know where the issue might be in and what is the value of TH_STORAGE_FREEMEM I need to set.

**Comment by vidda13** [comment]
The issue above is a run time issue. I was able to build a static library of cutorch and link it with torchdemo.so library

**Comment by culurciello** [comment]
If you are looking for the easiest way to deploy on embedded, or Android or iOs, thnets now contains also an easy stripped-version of openBLAS, so it is really easy to compile it on embedded devices: https://github.com/mvitez/thnets. We highly recommend it
