### ISSUE TITLE
Problem deploying on device with pre-trained net that uses newer 'nn' package.

### ISSUE THREAD

**Issue by yonadavs** [soumith/torch-android#15]
I got torch to run on my device, but have problems running my pre-trained net.
It loads fine, but when I try to use 'net:forward' it fails, due to a newer 'nn' package used to build the net, than what is included in torch-android-master.

I tried updating 'nn' manually, updating init.lua & init.c accordingly, but this didn't work because 'THRandom_uniform' now requires 3 input parameters.

I figured my torch for android must not have gotten its core files from my torch install. Should this be? Or is it supposed to use my latest torch version to create it?

I tried updating it manually too, that's when all hell broke loose..

**Comment by culurciello** [comment]
If you are looking for the easiest way to deploy on embedded, or Android or iOs, thnets now contains also an easy stripped-version of openBLAS, so it is really easy to compile it on embedded devices: https://github.com/mvitez/thnets. We highly recommend it

**Comment by soumith** [comment]
Just updated torch-android to latest packages, you shouldn't have an issue now.
