### ISSUE TITLE
link to submodule cunxx is broken

### ISSUE THREAD

**Issue by cramaiahmm** [soumith/torch-android#28]
git submodule update --init --recursive gives the following error:

Unable to checkout '29bf389a23e9d8cfd78ceda096917bf1fca3eeee' in submodule path 'distro/extra/cunnx'

**Comment by pilhokim** [comment]
For me, it complains on a different module, 'distro':

Unable to checkout 'e89d58b14f21f4d4caba9cc5a7a05722115cbc2e' in submodule path 'distro'

Update: I have kept trying the update and finally arrived at the same error reported above. Guess my update was terminated much earlier than @cramaiah

**Comment by fedor-chervinskii** [comment]
I have exactly the same error
`Unable to checkout '29bf389a23e9d8cfd78ceda096917bf1fca3eeee' in submodule path 'distro/extra/cunnx'`

**Comment by soumith** [comment]
see if https://github.com/soumith/torch-android/pull/32 fixed it.

**Comment by cramaiahmm** [comment]
Fixed, thanks. 

I'm now getting a CMAKE issue with cutorch/THC, I'll open a new issue if I can't figure it out.
