### ISSUE TITLE
net.forward value different between ubuntu(Openface nn4.small2.v1.t7) and Android.

### ISSUE THREAD

**Issue by Vincechen611** [soumith/torch-android#31]
We try to use torch-Android to load Openface nn4.small2.v1.t7 (apkbinary64) to get the net.forward value on android, but the result of net:forward function is different with Ubuntu. We are sure that the torch package on android is same as the package on Ubuntu.
Call you give us same suggest ?

**Comment by soumith** [comment]
how big is the difference? is it a minor difference with results varying within an epsilon?

**Comment by Vincechen611** [comment]
Hi @soumith  We find that the error is caused by our mistake.
We try to pass the image data from c to lua Instead of loading image file with torch image.load function, but we forgot to transform RGB value to byte for the FloatTensor...
Sorry for the trouble...

-Vince

**Comment by cshbli** [comment]
Hello @Vincechen611 I am also working on loading nn4.small2.v1.t7 on torch-Android and got error message "unknown Torch class <nn.Inception>". it seems that the "dpnn" package is required. Could you share me some details how to load nn4.small2.v1.t7? Thanks a lot!

**Comment by Vincechen611** [comment]
Hi @cshbli , dpnn and nn is required. If you still get error, maybe you can try to load nn4.small2.v1.t7 on a 32bit Ubuntu system and save it. 
-Vince

**Comment by cshbli** [comment]
Hi @Vincechen611, you are right. I was able to make it work after installing the dpnn. thanks anyway.

**Comment by perp** [comment]
I want to run openface demo on Android, The face recognition model requires dpnn. but I could not found dpnn in torch-android while torch7 has that. 
How did you install dpnn?
install distro using lua5.1

**Comment by perp** [comment]
I solved this problem
1. luarocks install dpnn on linux with torch7
2. copy dpnn module and moses.lua to torch android install/share/lua/5.1/
3. edit dpnn/init.lua replay torch.include('dpnn','xxx.lua') using require('dpnn.xxx')
4. then build android-demo

**Comment by kk291** [comment]
Hi perp,
I am also trying to run openface demo on Android. The step 3 you have written is not clear. Can you clarify?

**Comment by kk291** [comment]
Can someone share the steps for running openface demo on Android? How to install dpnn? In which location/folder should the openface model be kept? I am using the openface model from here https://cmusatyalab.github.io/openface/models-and-accuracies/ 

Is something else needed?
What does "try to load nn4.small2.v1.t7 on a 32bit Ubuntu system and save it. " mentioned above mean?

**Comment by perp** [comment]
Hi @kk291.
The dpnn module dose not exist if you git clone torch android directly.
you need install torch7 on your ubuntu first. then install dpnn module using "luarocks install dpnn"
I copied the dpnn module directly from torch7 to torch android but I got error “concatenate a nil value”.
then I replace the torch.include in init.lua file in dpnn folder using require like step 3.
then I build the android-demo and everything goes fine.
If you still have any problem feel free to contact me.
and if you want to load nn4.small2.v1.t7, using torch.load('nn4.small2.v1.t7','apkbinary64'),remember to add require torchandroid.

**Comment by kk291** [comment]
Hi @perp,

Thanks for your help. I have been able to make the change in dpnn/init.lua. I am able to use "require dpnn" in a .lua file now. Can you explain why/how these changes work? We do not have a libdpnn.so whereas there are libimage.so,libtorch.so etc. ..

**Comment by kk291** [comment]
Hi @soumith @perp ,

How are we supposed to pass arguments to a lua file in torch-android?

**Comment by xae217** [comment]
@perp @kk291 Did any of you get the open face models running? I am having trouble. I am getting the "concatenate a nil value" error mentioned above but cannot seem to be able to solve it
