### ISSUE TITLE
don't work ./build.sh  fatal error: torchandroid.h: No such file or directory

### ISSUE THREAD

**Issue by Sathen** [soumith/torch-android#34]
Try build android-demo project, but when start ./build.sh. I hava this error 

```
Updated local.properties
Updated file ./proguard-project.txt
Android NDK: WARNING: APP_PLATFORM android-23 is larger than android:minSdkVersion 14 in ./AndroidManifest.xml    
Android NDK: WARNING:jni/Android.mk:torchdemo: non-system libraries in linker flags: -lcunn -lTHCUNN -lcutorch -lnnx -limage -lnn -lTHNN -ltorch -lTH -lluaT -lluajit -ltorchandroid    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
[armeabi-v7a] Compile++ thumb: torchdemo <= torchdemo.cpp
jni/torchdemo.cpp:8:26: fatal error: torchandroid.h: No such file or directory
 #include "torchandroid.h"
                          ^
compilation terminated.
```

**Comment by borisfom** [comment]
Did you run build.sh in the root directory first ?

**Comment by Sathen** [comment]
[  9%] Linking C executable ../../../../../install/bin/luajit
cd /Users/aleksii/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_link_script CMakeFiles/luajit.dir/link.txt --verbose=1
/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -Wno-psabi --sysroot=/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname,libluajit.so -o ../../../../../install/libs/armeabi-v7a/libluajit.so CMakeFiles/libluajit.dir/src/ljamalg.c.o CMakeFiles/libluajit.dir/lj_vm.S.o  -L/Users/aleksii/torch-android/install/libs/armeabi-v7a  -L/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/lib -ldl -lm  "/Users/aleksii/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc  -Wno-psabi --sysroot=/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG   -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,nocopyreloc -fPIE -pie -Wl,--export-dynamic CMakeFiles/luajit.dir/src/luajit.c.o CMakeFiles/luajit.dir/src/ljamalg.c.o CMakeFiles/luajit.dir/lj_vm.S.o -o ../../../../../install/bin/luajit  -L/Users/aleksii/torch-android/install/libs/armeabi-v7a  -L/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/lib  -ldl -lm  "/Users/aleksii/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
CMakeFiles/libluajit.dir/src/ljamalg.c.o:ljamalg.c:function luaJIT_profile_start: error: undefined reference to 'sigemptyset'
collect2: error: ld returned 1 exit status
make[2]: **\* [../install/libs/armeabi-v7a/libluajit.so] Error 1
make[1]: **\* [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
CMakeFiles/luajit.dir/src/luajit.c.o:luajit.c:function laction: error: undefined reference to 'signal'
CMakeFiles/luajit.dir/src/luajit.c.o:luajit.c:function dotty: error: undefined reference to 'signal'
CMakeFiles/luajit.dir/src/luajit.c.o:luajit.c:function dotty: error: undefined reference to 'signal'
CMakeFiles/luajit.dir/src/luajit.c.o:luajit.c:function pmain: error: undefined reference to 'signal'
CMakeFiles/luajit.dir/src/ljamalg.c.o:ljamalg.c:function luaJIT_profile_start: error: undefined reference to 'sigemptyset'
collect2: error: ld returned 1 exit status
make[2]: **\* [../install/bin/luajit] Error 1
make[1]: **\* [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: **\* [all] Error 2

**Comment by borisfom** [comment]
Please try again and let us know if still having issues!

**Comment by Sathen** [comment]
Now I have this error `/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -Wno-psabi --sysroot=/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname, -o ../../../../install/libs/armeabi-v7a/libpaths.so CMakeFiles/paths.dir/paths.c.o  -L/Users/aleksii/torch-android/install/libs/armeabi-v7a  -L/Users/aleksii/torch-android/install/lib -lluajit  "/Users/aleksii/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
cd /Users/aleksii/torch-android/build/distro/pkg/sundown && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_link_script CMakeFiles/sundown.dir/link.txt --verbose=1
/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -Wno-psabi --sysroot=/Users/aleksii/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-allow-shlib-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname, -o ../../../../install/libs/armeabi-v7a/libsundown.so CMakeFiles/sundown.dir/src/autolink.c.o CMakeFiles/sundown.dir/src/buffer.c.o CMakeFiles/sundown.dir/src/markdown.c.o CMakeFiles/sundown.dir/src/stack.c.o CMakeFiles/sundown.dir/html/houdini_href_e.c.o CMakeFiles/sundown.dir/html/houdini_html_e.c.o CMakeFiles/sundown.dir/html/html.c.o CMakeFiles/sundown.dir/html/html_smartypants.c.o  -L/Users/aleksii/torch-android/install/libs/armeabi-v7a -lluajit  "/Users/aleksii/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"
/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: -soname: must take a non-empty argument
collect2: error: ld returned 1 exit status
make[2]: *** [../install/libs/armeabi-v7a/libpaths.so] Error 1
make[1]: *** [distro/pkg/paths/CMakeFiles/paths.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Nothing to be done for`distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build'.
/Users/aleksii/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: -soname: must take a non-empty argument
collect2: error: ld returned 1 exit status
make[2]: **\* [../install/libs/armeabi-v7a/libsundown.so] Error 1
make[1]: **\* [distro/pkg/sundown/CMakeFiles/sundown.dir/all] Error 2
[ 34%] Built target TH
make: **\* [all] Error 2
`
But before I had error like from here https://github.com/soumith/torch-android/issues/47
So I copy  libsupc++.a from ndk, and now I have the next error

**Comment by borisfom** [comment]
Please try again and let us know if still having issues!

**Comment by borisfom** [comment]
Build is fixed now.
