### ISSUE TITLE
Add cltorch module?

### ISSUE THREAD

**Issue by awolfmann** [soumith/torch-android#39]
Hello, 
I'm trying to add cltorch module to provide OpenCL support, since cuda is not so usefull for phones. 
As far as i see, you are just using the Self-contained Torch distro, with the modules it includes, and compile them in build.sh "generically", so you don't change anything else inside the cmake of each module.
What i did was add cltorch to torch-android/distro/extra and added 'ADD_SUBDIRECTORY(cltorch)' on the CMakeLists.txt

When i try to run ./build.sh i get this error:
CMake Error at distro/extra/cltorch/CMakeLists.txt:60 (ADD_DEPENDENCIES):
  Cannot add target-level dependencies to non-existent target
  "cltorchtensormathwrap".

It seems that cannot find the sub dependecies of cltorch

Any idea how to solve?

**Comment by soumith** [comment]
this is not a trivial exercise, unless you are really good with build systems dont attempt this.
