### ISSUE TITLE
Can't build torch-android

### ISSUE THREAD

**Issue by Firmamenter** [soumith/torch-android#40]
Hi, 

I’m trying to build torch-android and get some issues. When I run the build.sh, the script can not change directory to distro/exe and it comes out some buildvm_arm.dasc errors. Here is the Log
[Log at 2016-04-15 10.05.34.txt](https://github.com/soumith/torch-android/files/220253/Log.at.2016-04-15.10.05.34.txt)
. Can somebody help me?

**Comment by borisfom** [comment]
You need to install Nvidia NVPACK (really no use of Torch on Android without GPU). here's what cmake should get :
Android NDK found at: /home/bfomitchev/NVPACK/android-ndk-r10e/

**Comment by borisfom** [comment]
I mean, your errors are probably due to ndk-11 changes we did not test - but it would fail not finding CUDA later anyway. So the best course would be to install NVPACK.

**Comment by Firmamenter** [comment]
Thx, @borisfom! Learned something. But still got some problems after installing NVPACK. Here is the 
[Log at 2016-04-17 11.26.36.txt](https://github.com/soumith/torch-android/files/222495/Log.at.2016-04-17.11.26.36.txt). And I don't quite understand the second step -- 'open build.sh and modify ANDROID_NDK to your android ndk path'. Did you mean add this [export ANDROID_NDK="/home/jurh/disk/NVPACK/android-ndk-r10e"] into the build.sh?

**Comment by borisfom** [comment]
I have fixed README.md - no you don't have to modify anything if NVPACK nvcc is in PATH.
As for your error: you should run ./clean.sh to remove all previous build artifacts, as per the error message:
CMake Error at /home/jurh/disk/chenda/torch-android_1/cmake/android.toolchain.cmake:492 (message):
  It is not possible to change the path to the NDK on subsequent CMake run.
  You must remove all generated files from your build folder first.

**Comment by Firmamenter** [comment]
I have already run ./clean.sh, but it didn't work. Anyway, I re-downloaded the repository and it works now. Thanks for your help @borisfom !
