### ISSUE TITLE
Android-demo issues

### ISSUE THREAD

**Issue by Firmamenter** [soumith/torch-android#43]
Hi, 

I encountered some problems when building android demos. I can successfully build android-demo, but when I tried to build android-demo-cifar and facedetector_e-lab, I got some errors. Here are the Logs: 
[Log at 2016-04-21 10.18.08.txt](https://github.com/soumith/torch-android/files/229116/Log.at.2016-04-21.10.18.08.txt) and [Log at 2016-04-21 10.21.57.txt](https://github.com/soumith/torch-android/files/229118/Log.at.2016-04-21.10.21.57.txt). 
Another issue  is that after I transferred the TorchDemo-debug.apk(built from android-demo) to Genymotion virtual device and installed it, I could't open it. It comes out errors, you can see the 
[Log.txt](https://github.com/soumith/torch-android/files/229129/Log.txt). 
By the way, I use server to build android demos so I choose to just download the TorchDemo-debug.apk and install it locally on virtual device, instead of connecting android phone in debugging mode and automatically installing the apk. Besides, are there any specific requirements for the virtual device so that I can run the TorchDemo app?

Can somebody help me? Many thanks for your help.

**Comment by borisfom** [comment]
You are right, only one demo app works now. I should add a note.
The app is being built in ARM mode so it won't work on virtual device:
4-20 22:59:34.949 1713-1713/com.torch.torchdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.torch.torchdemo, PID: 1713
                                                                   java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.torch.torchdemo-1/lib/arm/libtorchandroid.so" has unexpected e_machine: 40

You may try to change the build settings for the virtual device but I doubt it will work, considering by default Torch requires CUDA .

**Comment by Firmamenter** [comment]
Thanks, did you mean I need a real android phone with CUDA installed on it?

**Comment by borisfom** [comment]
Yes. You may try disabling CUDA by WITH_CUDA=False but frankly this option won't give you anywhere close to usable speed.

**Comment by Firmamenter** [comment]
Hi, 

I could only find two sorts of mobile devices that are suitable for running this android-demo, since only Tegra K1 and Tegra X1 can support CUDA. You can see [here](http://www.nvidia.com/object/tegra-phones-tablets.html)  .
So, could you please tell me which device is your test platform? Are there any other phones that support cuda?

**Comment by borisfom** [comment]
Right, only K1 and X1 support CUDA as far as I know.

**Comment by Firmamenter** [comment]
Hi,

If disabling CUDA by WITH_CUDA=OFF, then I got this:
./build.sh: line 129: cd: distro/extra/cutorch: No such file or directory

Do you have any idea?

**Comment by LH23** [comment]
in build.sh I added a conditional at the end in the  "cd distro/extra/cutorch" line to fix this error

```
if [[ "$WITH_CUDA" == "ON" ]]; then
    (cd distro/extra/cutorch && $MAKE $MAKEARGS install) || exit 1
fi
```
