### ISSUE TITLE
apk release

### ISSUE THREAD

**Issue by monolithpl** [soumith/torch-android#46]
hi! i'm very interested in your project but just looking at the issues folks have with building it without errors is a bit discouraging. how about posting a ready-made apk (two, actually, one for for CUDA and one for CPU), so people can get started actually building something interesting and not wasting time with debugging the code?

**Comment by sixsamuraisoldier** [comment]
Yeah, would love this as well.

**Comment by paramsen** [comment]
Getting rather convinced that this lib can't be built, by anyone. I've had 30% of the open issues here during my continuous builds, spent like ~16h trying to get this going, no kidding. The repo owners aren't answering anyway so I'd say this is quite abandoned.

**Comment by culurciello** [comment]
just use: https://github.com/e-lab/apps-android

**Comment by borisfom** [comment]
Build issues should be fixed, please try again.

**Comment by monolithpl** [comment]
sorry but the issue was to release a ready-made apk in the releases section of github to broaden the appeal and save folks time & effort building the apk. this hasn't been done, so please don't close this issue as "fixed".
