### ISSUE TITLE
Invalid iTorch submodule in distro

### ISSUE THREAD

**Issue by chenguangshen** [soumith/torch-android#48]
The submodule distro @ 3a30a55 in torch-android contains an invalid pointer to iTorch. The current master branch of borisfom/distro (@ 3538b9f) defines the correct iTorch submodule.

I wonder if distro in torch-android should be updated to point to the latest commit.

**Comment by borisfom** [comment]
Fixed by https://github.com/soumith/torch-android/pull/49
