### ISSUE TITLE
Broken submodule

### ISSUE THREAD

**Issue by malzantot** [soumith/torch-android#50]
Hi,

When I try to update the project submodules using
`git submodule update --init --recursive`

I get the following error message :

> fatal: reference is not a tree: 43a5dfacfc310aab31f81654cd1b143ad9ec2b1c
> Unable to checkout '43a5dfacfc310aab31f81654cd1b143ad9ec2b1c' in submodule path 'distro/extra/cutorch'
> Failed to recurse into submodule path 'distro'

**Comment by borisfom** [comment]
Should be fixed now.
