### ISSUE TITLE
Cannot load libcutorch.so in android demo

### ISSUE THREAD

**Issue by chenguangshen** [soumith/torch-android#53]
After successfully building torch-android (ARCH=v7n, Cuda on, commit 8b7ff4e) and the android demo, starting the compiled app on Android will cause an error both in adb logcat and on the UI screen: 

```
05-18 19:07:19.813 3160-3160/com.torch.torchdemo I/torchdemo: Error doing resource: main.lua:[string "cutorch"]:2: cannot load '/data/app/com.torch.torchdemo-1/lib/arm/libcutorch.so'
```

The same error happened on a Tegra device (NVIDIA Tegra K1 Tablet, Android 6.0.1) and a non-Tegra device (LG Nexus 5X, Android 6.0.1). Using adb shell I can actually see the library file libcurtorch.so exists in the above path.

One possible reason might be that I have not pushes Cuda toolkit to my device since CodeWorks requires adb root access to perform the push. My understanding is that the compiled demo app should be self-contains in terms of execution, and the phone-side toolkit is only used for profiling. Please do correct me if I'm wrong.

Thanks a lot!

**Comment by borisfom** [comment]
No, current setup assumes you push CUDA libraries (not the whole toolkit, just cudart, cuda, currant, cublas, and also CUDNN5, to the device yourself.
If you have issues pushing them to system directory, just copy them into the demo app lib area.

**Comment by chenguangshen** [comment]
Thanks for the reply @borisfom . 

I tried pushing these libraries to the app lib folder and was able to get rid of the previous error. However there's a new error:

```
05-19 15:51:16.573 6159-6159/com.torch.torchdemo I/torchdemo: Error doing resource: main.lua:[string "nn/THNN"]:109: cuda runtime error (8) : invalid device function at path_to/torch-android/distro/extra/cutorch/lib/THC/THCTensorMath.cu:26
```

The error seems to be caused by incorrect CUDA/CUDNN library causing certain CUDA function unavailable (line 26 of THCTensorMath.cu is `THCudaCheck(cudaGetLastError())`).

I was using CUDA 7.0 and CUDNN v4 (there's not Android library for CUDNN v5 as of right now on NVIDIA website), and a NVIDIA Shield K1 with Tegra K1 and Android 6.0.1. Since officially CodeWorks only supports CUDA 6.5 on Shield K1, I also tried CUDA 6.5 + CUDNN v4 but got the same error.

Can I ask what version of CUDA/CUDNN and what hardware device are you using for the android demo?  Is there any public available resource to download CUDNN v5 for Android or for building from sources?

Thanks!

**Comment by borisfom** [comment]
Right, we only have CUDNN R4 on Android. Switched to R4 branch of distro.
Please try again.

**Comment by borisfom** [comment]
Do you still have the issue with CUDNN5 ?

**Comment by paramsen** [comment]
Seems to be the same issue as the one I just reported #88

**Comment by borisfom** [comment]
Versioning libs load fixed. For CUDNN, you do need CUDNN5.
