### ISSUE TITLE
Broken submodule (again)

### ISSUE THREAD

**Issue by czhang96** [soumith/torch-android#55]
When running git `git submodule update --init --recursive` , I get the following error:

`fatal: reference is not a tree: 0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a
fatal: reference is not a tree: 43a5dfacfc310aab31f81654cd1b143ad9ec2b1c
Unable to checkout '0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a' in submodule path 'distro/extra/cunn'
Unable to checkout '43a5dfacfc310aab31f81654cd1b143ad9ec2b1c' in submodule path 'distro/extra/cutorch'
Failed to recurse into submodule path 'distro'`

I've tried 
`git submodule foreach --recursive 'git submodule sync'`
 `git submodule update --recursive` and `git submodule sync`

Were the commits in the submodules committed/pushed?

Temporary workaround is to clone specific submodule manually

**Comment by borisfom** [comment]
Should be working now.
