### ISSUE TITLE
couldn't checkout submodule

### ISSUE THREAD

**Issue by perp** [soumith/torch-android#58]
root@perp:~/work/torch-android/distro# ./install.sh 
Prefix set to /home/perp/work/torch-android/distro/install
fatal: reference is not a tree: 0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a
fatal: reference is not a tree: 43a5dfacfc310aab31f81654cd1b143ad9ec2b1c
Unable to checkout '0ccd0cb024c2cb980ed2298f5f404cfd65c4eb1a' in submodule path 'extra/cunn'
Unable to checkout '43a5dfacfc310aab31f81654cd1b143ad9ec2b1c' in submodule path 'extra/cutorch'

**Comment by perp** [comment]
1. Change the build.sh WITH_CUDA="OFF"
2. need some head files of 32bit ubuntu. my OS is ubuntu 14.04 64bit

**Comment by borisfom** [comment]
Should be fixed now.
