### ISSUE TITLE
Build lastest torch7

### ISSUE THREAD

**Issue by quanhua92** [soumith/torch-android#6]
Hi, I want to use the lastest torch7 on android device. The current src folder in this repo looks like 2 year ago. Can you explain same steps to upgrade to lastest torch7?
Thank you very much

**Comment by nicholas-leonard** [comment]
If it is just Lua code, you can copy the modified lua scripts from the main torch to the android torch. Make sure to update the commensurate init.lua file for new files. For C, its a similar idea. @soumith might have a programmatic way to do this, but I just do it manually for every missing or out of data nn.Module and add the torch7 dependencies (say torch.view, torch.isTensor, etc).
