### ISSUE TITLE
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found

### ISSUE THREAD

**Issue by huanggengxin** [soumith/torch-android#60]
will@Will-Air ~/torch-android $ ./build.sh
Android NDK found at: /home/will/NVPACK/android-ndk-r10e/
INSTALL_DIR=/home/will/torch-android/install
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

```
WITH_CUDA
```

-- Build files have been written to: /home/will/torch-android/distro/extra/FindCUDA/build
 -------------- Configuring DONE ---------------
/usr/bin/cmake -H/home/will/torch-android/distro/extra/FindCUDA -B/home/will/torch-android/distro/extra/FindCUDA/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/will/torch-android/distro/extra/FindCUDA/build/CMakeFiles /home/will/torch-android/distro/extra/FindCUDA/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/will/torch-android/distro/extra/FindCUDA/build'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/will/torch-android/distro/extra/FindCUDA/build'
/usr/bin/cmake -E cmake_progress_start /home/will/torch-android/distro/extra/FindCUDA/build/CMakeFiles 0
make -f CMakeFiles/Makefile2 preinstall
make[1]: Entering directory`/home/will/torch-android/distro/extra/FindCUDA/build'
make[1]: Nothing to be done for `preinstall'.
make[1]: Leaving directory`/home/will/torch-android/distro/extra/FindCUDA/build'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Installing: /home/will/torch-android/install/share/cmake/torch/FindCUDA.cmake
-- Up-to-date: /home/will/torch-android/install/share/cmake/torch/FindCudaArch.cmake
-- Installing: /home/will/torch-android/install/share/cmake/torch/FindCUDA/make2cmake.cmake
-- Installing: /home/will/torch-android/install/share/cmake/torch/FindCUDA/parse_cubin.cmake
-- Installing: /home/will/torch-android/install/share/cmake/torch/FindCUDA/run_nvcc.cmake
-- Installing: /home/will/torch-android/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake
FindCuda installed
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

```
WITH_CUDA
```

-- Build files have been written to: /home/will/torch-android/external/libpng/build
 -------------- Configuring DONE ---------------
/usr/bin/cmake -H/home/will/torch-android/external/libpng -B/home/will/torch-android/external/libpng/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/will/torch-android/external/libpng/build/CMakeFiles /home/will/torch-android/external/libpng/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/depend
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
cd /home/will/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build/CMakeFiles/png16.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/build
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/png16.dir/build'.
make[2]: Leaving directory`/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/external/libpng/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
[ 45%] Built target png16
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/depend
make[2]: Entering directory `/home/will/torch-android/external/libpng/build'
cd /home/will/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build/CMakeFiles/png16_static.dir/DependInfo.cmake --color=
make[2]: Leaving directory`/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/build
make[2]: Entering directory `/home/will/torch-android/external/libpng/build'
make[2]: Nothing to be done for`CMakeFiles/png16_static.dir/build'.
make[2]: Leaving directory `/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/external/libpng/build/CMakeFiles  18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
[ 91%] Built target png16_static
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/depend
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
cd /home/will/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build/CMakeFiles/pngstest.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/build
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/pngstest.dir/build'.
make[2]: Leaving directory`/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/external/libpng/build/CMakeFiles  35
[ 94%] Built target pngstest
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/depend
make[2]: Entering directory `/home/will/torch-android/external/libpng/build'
cd /home/will/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build/CMakeFiles/pngtest.dir/DependInfo.cmake --color=
make[2]: Leaving directory`/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/build
make[2]: Entering directory `/home/will/torch-android/external/libpng/build'
make[2]: Nothing to be done for`CMakeFiles/pngtest.dir/build'.
make[2]: Leaving directory `/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/external/libpng/build/CMakeFiles  36
[ 97%] Built target pngtest
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/depend
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
cd /home/will/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build /home/will/torch-android/external/libpng/build/CMakeFiles/pngvalid.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/will/torch-android/external/libpng/build'
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/build
make[2]: Entering directory`/home/will/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/pngvalid.dir/build'.
make[2]: Leaving directory`/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/external/libpng/build/CMakeFiles  37
[100%] Built target pngvalid
make[1]: Leaving directory `/home/will/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_start /home/will/torch-android/external/libpng/build/CMakeFiles 0
make -f CMakeFiles/Makefile2 preinstall
make[1]: Entering directory`/home/will/torch-android/external/libpng/build'
make[1]: Nothing to be done for `preinstall'.
make[1]: Leaving directory`/home/will/torch-android/external/libpng/build'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Up-to-date: /home/will/torch-android/install/lib/libpng16.so.16.20.0
-- Up-to-date: /home/will/torch-android/install/lib/libpng16.so.16
-- Up-to-date: /home/will/torch-android/install/lib/libpng16.so
-- Up-to-date: /home/will/torch-android/install/lib/libpng16.a
-- Up-to-date: /home/will/torch-android/install/lib/libpng.so
-- Up-to-date: /home/will/torch-android/install/lib/libpng.a
-- Up-to-date: /home/will/torch-android/install/include/png.h
-- Up-to-date: /home/will/torch-android/install/include/pngconf.h
-- Up-to-date: /home/will/torch-android/install/include/pnglibconf.h
-- Up-to-date: /home/will/torch-android/install/include/libpng16/png.h
-- Up-to-date: /home/will/torch-android/install/include/libpng16/pngconf.h
-- Up-to-date: /home/will/torch-android/install/include/libpng16/pnglibconf.h
-- Up-to-date: /home/will/torch-android/install/bin/libpng-config
-- Up-to-date: /home/will/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/will/torch-android/install/share/man/man3/libpng.3
-- Up-to-date: /home/will/torch-android/install/share/man/man3/libpngpf.3
-- Up-to-date: /home/will/torch-android/install/share/man/man5/png.5
-- Up-to-date: /home/will/torch-android/install/lib/pkgconfig/libpng.pc
-- Up-to-date: /home/will/torch-android/install/bin/libpng-config
-- Up-to-date: /home/will/torch-android/install/lib/pkgconfig/libpng16.pc
-- Up-to-date: /home/will/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/will/torch-android/install/lib/libpng/libpng16.cmake
-- Installing: /home/will/torch-android/install/lib/libpng/libpng16-noconfig.cmake
libpng installed
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[1]: Entering directory `/home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from host/buildvm.h:13,
                 from host/buildvm_peobj.c:9:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
 #include <asm/errno.h>
                       ^
compilation terminated.
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from host/buildvm.h:13,
                 from host/buildvm_asm.c:6:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
 #include <asm/errno.h>
                       ^
compilation terminated.
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from host/buildvm.h:13,
                 from host/buildvm_fold.c:6:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
 #include <asm/errno.h>
                       ^
compilation terminated.
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from host/buildvm.h:13,
                 from host/buildvm_lib.c:6:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
 #include <asm/errno.h>
                       ^
compilation terminated.
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from host/minilua.c:40:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
 #include <asm/errno.h>
                       ^
compilation terminated.
make[1]: *** [host/buildvm_peobj.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [host/buildvm_asm.o] Error 1
make[1]: *** [host/buildvm_lib.o] Error 1
make[1]: *** [host/buildvm_fold.o] Error 1
make[1]: *** [host/minilua.o] Error 1
make[1]: Leaving directory`/home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
make: **\* [default] Error 2
Done installing Lua
-- LuaJIT Target: arm
-- LuaJIT target arm
-- Using system lua for generating dynasm via: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua
-- Executing command: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/dynasm/dynasm.lua -D;JIT;-D;FFI;-D;DUALNUM;-D;FPU -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/buildvm_arch.h /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/vm_arm.dasc
-- LUA_INCDIR: /home/will/torch-android/install/include
-- LUA_LIBDIR: /home/will/torch-android/install/lib
-- LUA_BINDIR: /home/will/torch-android/install/bin
-- LUALIB: /home/will/torch-android/install/libs/armeabi-v7a/libluajit.so
-- LUADIR: /home/will/torch-android/install/share/lua/5.1/
-- LIBDIR: /home/will/torch-android/install/lib/lua/5.1/
-- LUA_BINDIR: /home/will/torch-android/install/bin
-- SCRIPTS_DIR: /home/will/torch-android/install/bin
-- Compiling with OpenMP support
-- Compiling with OpenMP support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this on this machine.
-- No OMAP4 processor on this on this machine.
-- Atomics: using pthread
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- LAPACK requires BLAS
-- Cannot find a library with LAPACK API. Not using LAPACK.
-- C inline is supported (inline)
-- Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- Compiling with OpenMP support
WARNING: Could not find JPEG libraries, JPEG wrapper will not be installed
-- Compiling with OpenMP support
-- OpenMP Found with compiler flag : -fopenmp
-- Including android directory: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/will/torch-android/build
 -------------- Configuring DONE ---------------
cd /home/will/torch-android/build && /usr/bin/cmake -H/home/will/torch-android -B/home/will/torch-android/build --check-build-system CMakeFiles/Makefile.cmake 0
cd /home/will/torch-android/build && /usr/bin/cmake -E cmake_progress_start /home/will/torch-android/build/CMakeFiles /home/will/torch-android/build/distro/exe/CMakeFiles/progress.marks
cd /home/will/torch-android/build && make -f CMakeFiles/Makefile2 distro/exe/all
make[1]: Entering directory `/home/will/torch-android/build'
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/depend
make -f distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build.make distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/depend
make[2]: Entering directory`/home/will/torch-android/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 21
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 15
make[2]: Entering directory `/home/will/torch-android/build'
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 31
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 16
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 25
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 26
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 27
[  5%] [ 10%] [ 15%] /usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 28
[ 21%] [ 26%] [ 31%] [ 42%] [ 42%] Generating vmdef.lua
Generating vmdef.lua
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m vmdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/vmdef.lua src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m vmdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/vmdef.lua src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
Generating lj_vm.S
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/vmdef.lua] Error 127
make[2]: *** Waiting for unfinished jobs....
/usr/bin/cmake -E cmake_progress_report /home/will/torch-android/build/CMakeFiles 17
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/vmdef.lua] Error 127
make[2]: *** Waiting for unfinished jobs....
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m elfasm -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_vm.S
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
Generating lj_vm.S
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_vm.S] Error 127
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m elfasm -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_vm.S
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_vm.S] Error 127
Generating lj_ffdef.h
Generating lj_ffdef.h
Generating lj_libdef.h
Generating lj_bcdef.h
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m ffdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_ffdef.h src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m libdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_libdef.h src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m ffdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_ffdef.h src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m bcdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_bcdef.h src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_libdef.h] Error 127
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_ffdef.h] Error 127
/bin/sh: 1: [ 47%] /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_ffdef.h] Error 127
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/lj_bcdef.h] Error 127
make[2]: Leaving directory`/home/will/torch-android/build'
make[1]: **\* [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
Generating lj_bcdef.h
cd /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1 && /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm -m bcdef -o /home/will/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/lj_bcdef.h src/lib_base.c src/lib_math.c src/lib_bit.c src/lib_string.c src/lib_table.c src/lib_io.c src/lib_os.c src/lib_package.c src/lib_debug.c src/lib_jit.c src/lib_ffi.c
/bin/sh: 1: /home/will/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/buildvm: not found
make[2]: **\* [distro/exe/luajit-rocks/luajit-2.1/lj_bcdef.h] Error 127
make[2]: Leaving directory `/home/will/torch-android/build'
make[1]: *** [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/all] Error 2
make[1]: Leaving directory`/home/will/torch-android/build'
make: **\* [all] Error 2

**Comment by huanggengxin** [comment]
Sorry.I come here again.

**Comment by huanggengxin** [comment]
help!

**Comment by dioververa** [comment]
If on ubuntu, install the following packages: `sudo apt-get install libx32gcc-4.8-dev libc6-dev-i386`

**Comment by borisfom** [comment]
I have found one also may need this: sudo apt-get install linux-libc-dev:i386
