### ISSUE TITLE
Demo app fails to build, cant find -lnn

### ISSUE THREAD

**Issue by czhang96** [soumith/torch-android#61]
`[armeabi-v7a] Compile thumb  : torchdemo <= android_fopen.c
[armeabi-v7a] SharedLibrary  : libtorchdemo.so
/home/chris/NVPACK/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lnn
/home/chris/NVPACK/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lnn
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libtorchdemo.so] Error 1`

Cant find -lnn, even though I've run `./build.sh` in the root directory already

Any help?

**Comment by czhang96** [comment]
To solve the issue I just remove `-lnn` dependency and use `-lnnx` instead

**Comment by huanggengxin** [comment]
Could you tell me what can I do ?
nnx 0.1-1 is now built and installed in /home/will/torch/install/ (license: BSD)
I also install nn and nnx 
But the question is still exist.
Wait for your precious answer.

**Comment by czhang96** [comment]
I'm not sure the root cause of the issue, but for me, nnx was installed and nn was not. But because nnx has all functionality of nn, I remove dependency `-lnn` in [Android.mk](https://github.com/soumith/torch-android/blob/master/demos/facedetector_e-lab/jni/Android.mk#L11),  remove any `require 'nn'` found in lua code, and instead use `require 'nnx'`

**Comment by huanggengxin** [comment]
Thany you very much.
