### ISSUE TITLE
build torch with Android NDK

### ISSUE THREAD

**Issue by perp** [soumith/torch-android#62]
I wrote a test.lua like this
require "image"
function f()
x = {1,2,3}
return x
end

I call this lua script in c++ and compile c++ code with ndk
but lua_dofile function could not load test.lua
if I cancel the line require "image" the result is OK

I saw there is a face detection example using inittorch, the parameter is AAssetManager, I don't want to use this stuff,because I just need to compile the code with NDK to generate an executable.

**Comment by perp** [comment]
**_my lua file is:_**
require 'torchandroid'
require 'torch'
require 'nn'
require 'dpnn'
require 'image'
function f() 
   t = {0.1,0.2,0.3,0.4}
   return t  
end

**_my c file is_** 
#include        "lua.h"
#include        "lualib.h"
#include        "lauxlib.h"

  void print_table(lua_State *L) 
  {
          lua_getglobal(L,"f");
          lua_call(L,0,1);
          int n = lua_gettop(L);
          printf("stack size:%d\n",n);
          lua_pushnil(L);
          while(lua_next(L,-2))
          {  
                  if(lua_isnumber(L,-1))
                  {  
                          float x = (float)lua_tonumber(L,-1);
                          printf("x:%.3f\n",x);
                  }   

```
              lua_pop(L,1);
      }   
```

  }

  /_the lua interpreter_/
  lua_State\* L;
  int main(int argc, char *argv[])
  {
        int sum;
          L = luaL_newstate();
          luaL_openlibs(L);
          if( luaL_dofile(L, "test.lua"))
          {  
             printf("load file failed %s\n","test.lua");
          }  
          print_table(L);
          lua_close(L);
          return 0;
  }

**_the result is_** 
PANIC: unprotected error in call to Lua API (attempt to call a nil value)

**Comment by kk291** [comment]
Hi perp,

I am also trying to write c++ code (making use of torch) and build an executable using NDK. Not sure how to go about this. I tried the code given here. Getting the same error. Have you got it working?
