### ISSUE TITLE
cannot find -lnn

### ISSUE THREAD

**Issue by huanggengxin** [soumith/torch-android#63]
will@will-Alienware-14:~/torch-android/demos/android-demo-cifar/application$ bash build.sh
Updated local.properties
Updated file ./proguard-project.txt
Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 15 in ./AndroidManifest.xml  
Android NDK: WARNING:jni/Android.mk:torchdemo: non-system libraries in linker flags: -lluaT -lluajit -lTH -lTHNN -lnn -ltorch -lnnx -limage -ltorchandroid -lluaT -lluajit -lTH -lTHNN -lnn -ltorch -lnnx -limage -ltorchandroid  
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES  
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the  
Android NDK:     current module  
[armeabi-v7a] SharedLibrary  : libtorchdemo.so
/home/will/android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lnn
/home/will/android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lnn
collect2: error: ld returned 1 exit status
make: **\* [obj/local/armeabi-v7a/libtorchdemo.so] Error 1

on another hand,I installed nn .
-- Set runtime path of "/home/will/torch/install/lib/luarocks/rocks/nn/scm-1/lib/libTHNN.so" to "$ORIGIN/../lib:/home/will/torch/install/lib"
Updating manifest for /home/will/torch/install/lib/luarocks/rocks
nn scm-1 is now built and installed in /home/will/torch/install/ (license: BSD)

I spent much time to build this android demo of torch,but the quesion,one after another.

**Comment by czhang96** [comment]
I'm not sure the root cause of the issue, but for me, nnx was installed and nn was not. But because nnx has all functionality of nn, I remove dependency -lnn in Android.mk, remove any require 'nn' found in lua code, and instead use require 'nnx'

**Comment by spdd** [comment]
Same issue, does everyone know how to fix it?

**Comment by borisfom** [comment]
Please try again and let us know if still having issues!
