### ISSUE TITLE
Torch not fully utilizing CPU

### ISSUE THREAD

**Issue by czhang96** [soumith/torch-android#65]
Built torch-android without CUDA, CPU only. 

In android-demo, do not make any tensors cuda

Running the android-demo, android studio monitor shows only ~ 25% CPU usage. Any reason why it's not 100 (as it is when trying similar caffe-android ports)? I tried `torch.setnumthreads(4)`, but it doesn't seem to have done anything.

Why is this happening?

**Comment by arbuzz** [comment]
Experiencing the same

**Comment by ExenVitor** [comment]
It's the same problem with #68. You can try to compile OpenBlas.

**Comment by borisfom** [comment]
Torch itself using a single thread, so unless your program utilizes parallel OpenBLas etc. if would only use a single core.
