### ISSUE TITLE
Build successfully, but only "libnn.so" is missing

### ISSUE THREAD

**Issue by zhouyong64** [soumith/torch-android#71]
WITH_CUDA is configured to be "OFF". The build is run successfully without error. Most of the libs were created such as libTH.so, libTHNN.so, libnnx.so, libpaths.so, libluaT.so, libluajit.so. However, it seems that only "libnn.so" is missing. Is there any configuration that I should enable? Thanks so much.

**Comment by spdd** [comment]
Hi @zhouyong64 What are you solved this issue?
