### ISSUE TITLE
Build for demo apps failed  error: cannot find -lrt

### ISSUE THREAD

**Issue by viralparekh** [soumith/torch-android#75]
```
Updated local.properties
Updated file ./proguard-project.txt
Android NDK: WARNING: APP_PLATFORM android-23 is larger than android:minSdkVersion 14 in ./AndroidManifest.xml
[armeabi-v7a] SharedLibrary  : libtorchdemo.so
/home/viral/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: 
error: cannot find -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libtorchdemo.so] Error 1

```

**Comment by YaoQ** [comment]
I got the same issue, @viralparekh , have you fixed yet?

**Comment by Erhannis** [comment]
Oh, hey, this is the same issue I have.  Any fix?

**Comment by viralparekh** [comment]
@YaoQ  @Erhannis , this problem does not seem to be with code, it is because of librt.so file might be missing or may not have proper path. try to locate librt.so file on your system.

**Comment by Erhannis** [comment]
Ok; thanks!  I've since moved on to a different library, but hopefully this helps somebody else.

**Comment by viralparekh** [comment]
@Erhannis  what new library are you using for deep learning in mobile devices?
tensorflow ?

**Comment by Erhannis** [comment]
No, I'm using DeepLearning4Java (DL4J).  I'd tried it before, but the android example I found was old and broken.  I recently found a tutorial that works: http://progur.com/2017/01/how-to-use-deeplearning4j-on-android.html

**Comment by borisfom** [comment]
@Erhannis: the build should be fixed now, did you pull recent changes ?

**Comment by canneltigrou** [comment]
Hi,
I had the same problem, 
and into the file jni/Application.mk, I replace the flags -fopenmp   by  -lgomp
It works for me :-)
