### ISSUE TITLE
libpng16.so.16 not found

### ISSUE THREAD

**Issue by spdd** [soumith/torch-android#76]
I want to save Torch tensor as image, but I can't because libpng not loaded I got issue: **java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libpng16.so.16" needed by "libtorchdemo.so"; caused by library "libpng16.so.16 not found**

**Comment by xae217** [comment]
Having the same issue. Were you able to solve it?

**Comment by culurciello** [comment]
use this instead of this repo: https://github.com/e-lab/apps-android

**Comment by borisfom** [comment]
Fixed now.
