### ISSUE TITLE
Get a error: impossible constraint in 'asm'?

### ISSUE THREAD

**Issue by amazingyyc** [soumith/torch-android#79]
I get a error: impossible constraint in 'asm'. it looks like some asm code can't be used in NDK(just guess)? i found that the error occur in below,  Anyone has this error before?
static inline void cpuid(uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
{
#ifndef _MSC_VER
  uint32_t a = *eax, b, c, d;
  asm volatile ( "cpuid\n\t" : "+a"(a), "=b"(b), "=c"(c), "=d"(d) );

  *eax = a;
  *ebx = b;
  *ecx = c;
  *edx = d;
#else
  uint32_t cpuInfo[4];
  __cpuid(cpuInfo, *eax);
  *eax = cpuInfo[0];
  *ebx = cpuInfo[1];
  *ecx = cpuInfo[2];
  *edx = cpuInfo[3];
#endif
}

**Comment by BrianOn99** [comment]
@amazingyyc There is some related discussion in issue #74.  Many people have same problem as yours.  You are not alone.

**Comment by BrianOn99** [comment]
Hope the developers fix it asap!

**Comment by amazingyyc** [comment]
I think the reason is that: a asm code "asm volatile ( "cpuid\n\t" : "+a"(a), "=b"(b), "=c"(c), "=d"(d) );" in file simd.h is not supported in ARM. so annotation the function(TH_API void THVector_(vectorDispatchInit)();) in file TH/generic/THVector.h and file THVectorDispatch.c. it will work well.

**Comment by amazingyyc** [comment]
the above method is not fit the "torch-android". But works well in my own Android project that just include torch/TH and  torch/THNN. 
But I got another question: my own build project is very very slower than other 's. Should I set any parameter in my own building? @BrianOn99

**Comment by BrianOn99** [comment]
@amazingyyc I am not an a developer here.  I have never been able to run the demo app.  If it is possible, would you mind share how you build the app?  (Did you success?)

Nevertheless, I could give you some suggestion.  Some one has integrated openblas to torch-android: #68.  See if that can help you!

[Edit]
Sorry I may have misunderstood your question.  Did you mean your building process is slow or your app is slow?

**Comment by amazingyyc** [comment]
thank u for your apply. I do not run this demo app successfully either. I just run the only troch/TH and torch/THNN on android(the core of torch). The method has been mentioned: annotation the code "asm volatile ( "cpuid\n\t" : "+a"(a), "=b"(b), "=c"(c), "=d"(d) );".. 
By the way thank u for your advice about the openblas.

**Comment by borisfom** [comment]
I had a similar error. I resolved it by adding NEON_FOUND flash to true in the build script so that it builds for neon platform. 
I have updated both this repo and NVIDIA location, please try the trick above.

**Comment by BrianOn99** [comment]
Thanks @borisfom.  May I ask could the sample apps be build and run successfully now (without CUDA)?

**Comment by amazingyyc** [comment]
my app is slow compared other's THNN.so like prisma (the prisma app using the thnn too).

**Comment by amazingyyc** [comment]
update the code and the problem is gone(i do not know why)?!
But got another problem: error: 'THHalfVector_fill_DISPATCHTABLE' undeclared (first use in this function) #define THVector_(NAME) TH_CONCAT_4(TH,Real,Vector_,NAME)
I feel the world is going to dark 😩

**Comment by BrianOn99** [comment]
@amazingyyc Yeah, I have already opened the issue #78.
The "HalfVector" stuff are added for the CUDA backend, but it should be optional.

**Comment by monoeci** [comment]
I was having the same _impossible constraint_ error, and I can confirm that adding the neon flag resolved my issues. Specifically, in build.sh, I modified the export MAKEARGS line in build.sh as follows:

export MAKEARGS="-j$(getconf _NPROCESSORS_ONLN) -DNEON_FOUND=true"

This worked only without CUDA, and using the official torch distro instead in the _distro_ submodule/direcotry, as the one from nvidia does not currently compile on my system. I'll keep trying though.

**Comment by borisfom** [comment]
Please pull and try again.
