### ISSUE TITLE
cp: cannot stat ‘src/libs/armeabi-v7a/*.a’

### ISSUE THREAD

**Issue by thelinuxmaniac** [soumith/torch-android#8]
When running the build command, I get the following error:

```
$ ./build.sh
.........
Copying libraries
cp: cannot stat ‘src/libs/armeabi-v7a/*.a’: No such file or directory
done
.........
```

This error seems obvious to me because there isn't any "src/libs" directory in the source tree. Should I manually create the "src/libs" directory? If yes, where should I get its contents from?

**Comment by thedarkmatter** [comment]
Copy *.a files to lib folder as mentioned in  #3  and then update Android.mk when you compile android-demo similarly as mentioned in #7.
This should solve the problem.

**Comment by thelinuxmaniac** [comment]
Thanks, it works
