### ISSUE TITLE
Unrecognized command line option '-mfpu=neon'

### ISSUE THREAD

**Issue by Erhannis** [soumith/torch-android#81]
Well, https://github.com/soumith/torch-android/issues/74 has stopped occurring, which is hopefully good, but I now get the following error when I build:
aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=neon'

Specifically:

```
cd /home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH && /home/erhannis/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc  -DANDROID -DTH_EXPORTS -DUSE_PTHREAD_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -isystem /home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem /home/erhannis/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/erhannis/projects/torch-android/install/include -I/home/erhannis/projects/torch-android/distro/exe/luajit-rocks/luajit-2.1/src -I/home/erhannis/projects/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 -I/home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH -I/home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/TH -I/home/erhannis/projects/torch-android/distro/pkg/torch/lib/luaT -I/home/erhannis/projects/torch-android/build/distro/pkg/torch/lib/luaT  -mfpu=neon -D__NEON__ -Wno-psabi --sysroot=/home/erhannis/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -Werror=implicit-function-declaration -Werror=format -fopenmp -fopenmp -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG -fPIC   -o CMakeFiles/TH.dir/THGeneral.c.o   -c /home/erhannis/projects/torch-android/distro/pkg/torch/lib/TH/THGeneral.c
aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=neon'
distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/build.make:65: recipe for target 'distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THGeneral.c.o' failed
make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THGeneral.c.o] Error 1
make[2]: Leaving directory '/home/erhannis/projects/torch-android/build'
CMakeFiles/Makefile2:530: recipe for target 'distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all' failed
make[1]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

On Debian 8.6 (jessie), 64 bit

**Comment by Wesmania** [comment]
I found that removing the flag from cmake build files makes everything compile file. Apparently the flag is implicit when using the ndk.

**Comment by Erhannis** [comment]
@Wesmania I'm not having much luck figuring out which parts of which files I need to modify - could you be a little more specific?

**Comment by Wesmania** [comment]
@Erhannis try removing '-mfpu=neon' from cmake/android.toolchain.cmake:1251.
I'm no longer convinced that neon support is implicit, this might be just a workaround.

**Comment by Erhannis** [comment]
Huh.  That alone didn't work, but after cloning and git submodule init I grepped "mfpu=neon" and removed it from every single file I found it in, and it compiled.  Guess I'll go see if it actually runs.  Thanks!

**Comment by viralparekh** [comment]
@Erhannis , please  let us know if that works for you.  Thanks.

**Comment by Erhannis** [comment]
I can't build the demo; when I go to demos/android-demo and run ./build.sh I get the following:
```
Updated local.properties
Updated file ./proguard-project.txt
Android NDK: WARNING: APP_PLATFORM android-23 is larger than android:minSdkVersion 14 in ./AndroidManifest.xml
[armeabi-v7a] SharedLibrary  : libtorchdemo.so
/home/erhannis/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
/home/erhannis/Android/Sdk/ndk-bundle/build/core/build-binary.mk:702: recipe for target 'obj/local/armeabi-v7a/libtorchdemo.so' failed
make: *** [obj/local/armeabi-v7a/libtorchdemo.so] Error 1
```

**Comment by Erhannis** [comment]
I've tried it again, and remember now that there was an additional bug in between.  Maybe I'll split this off into its own issue, since it's not currently clear that this is a result of the mfpu=neon issue.

**Comment by paramsen** [comment]
Still getting this. 
Ubuntu 14.04 (x64) with https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip as said in the current "Requirements". 
CUDA=OFF in .build.sh.

I have no idea what the line (in the readme) "For NEON ARM CPU, you need to work around CMake bug by setting NEON_FOUND file in build.sh" means. 

Any news on this issue?

More output:

    cd /home/vagrant/torch-android/build/distro/pkg/torch/lib/TH && /home/vagrant/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc  -DANDROID -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DTH_EXPORTS -DUSE_PTHREAD_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -mfpu=neon -D__NEON__ -Wno-psabi --sysroot=/home/vagrant/ndk-bundle/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack -DDISABLE_POSIX_MEMALIGN -Werror=implicit-function-declaration -Werror=format -fopenmp -fopenmp -DTH_HAVE_THREAD -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG -fPIC -isystem /home/vagrant/ndk-bundle/platforms/android-21/arch-arm64/usr/include -isystem /home/vagrant/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/vagrant/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem /home/vagrant/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/vagrant/torch-android/install/include -I/home/vagrant/torch-android/distro/exe/luajit-rocks/luajit-2.1/src -I/home/vagrant/torch-android/build/distro/exe/luajit-rocks/luajit-2.1 -I/home/vagrant/torch-android/distro/pkg/torch/lib/TH -I/home/vagrant/torch-android/build/distro/pkg/torch/lib/TH -I/home/vagrant/torch-android/distro/pkg/torch/lib/luaT -I/home/vagrant/torch-android/build/distro/pkg/torch/lib/luaT    -o CMakeFiles/TH.dir/THTensor.c.o   -c /home/vagrant/torch-android/distro/pkg/torch/lib/TH/THTensor.c
    aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=neon'
    make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THStorage.c.o] Error 1
    aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=neon'
    aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=neon'
    make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THTensor.c.o] Error 1
    make[2]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/THAllocator.c.o] Error 1
    make[2]: Leaving directory `/home/vagrant/torch-android/build'
    make[1]: *** [distro/pkg/torch/lib/TH/CMakeFiles/TH.dir/all] Error 2
    make[1]: Leaving directory `/home/vagrant/torch-android/build'
    make: *** [all] Error 2

**Comment by Erhannis** [comment]
@paramsen Did you try removing every single reference to "-mfpu=neon" found in or under the android-torch root directory, after "git submodule --init --update" runs?  I don't know which one is the offender, or if I'm just shoving problems further down the line, but I simply manually replaced "-mfpu=neon" with "" everywhere grep found it, including text files, just to be sure.  Android-Torch then built, for me, though as I haven't been able to build the demo I can't say yet whether it actually _works_.

**Comment by paramsen** [comment]
@Erhannis Yes I just tried replacing all occurrences (again), ended up getting the error described in #74 instead which is a dead end afaik. So the build at least continued way beyond the "-mfpu=neon" error, so it might've been a partial solution. Here's a snippet for the substitution: 
`grep -rl . -e '-mfpu=neon' | xargs sed -i 's/-mfpu=neon//g'`

EDIT: The irony that you came here from #74 , how did solve it?

**Comment by paramsen** [comment]
I managed to build from a clean clone without substituting "-mfpu=neon" by installing required ARM sources `sudo apt-get install gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf  libgtk2.0-dev  libjpeg-dev libpng-dev libtiff-dev libjasper-dev -y`. Then I did the process described in README.md again without hitting any "-mfpu=neon" -related problems.
Got some other problems in the build process though, better open another issue.

**Comment by borisfom** [comment]
Please pull and try again.

**Comment by paramsen** [comment]
@borisfom Works now, thanks for taking your time to fix this. I encountered a new issue when building the demo app, probably some stuff changed now in the update creating a minor issue. I'll open an issue.

[Verified on Ubuntu 14.04 with CUDA]

**Comment by arnav2** [comment]
Did anyone figure out how to build it without actually removing it. I would like to use neon for the optimization.
