### ISSUE TITLE
Android fails to load versioned shared external libraries

### ISSUE THREAD

**Issue by Wesmania** [soumith/torch-android#82]
Right now shared libraries like libTH are built versioned. When packed in the apk, the version is stripped and Android fails to load the libraries. One workaround is to delete the VERSION and SOVERSION attributes from CMakeLists of problematic libraries.

**Comment by culurciello** [comment]
use this instead of this repo: https://github.com/e-lab/apps-android

**Comment by borisfom** [comment]
@culurciello : Please stop.

**Comment by BrianOn99** [comment]
@culurciello I agree with @borisfom.  It is insulting to advertise your own repo here, instead of making any suggestion for improvement or PR.  It would be better if you can point out how you fix this issue in your own repo.

**Comment by culurciello** [comment]
Sure guys, just wanted to help. In SOME cases: https://github.com/e-lab/apps-android it may be easier to use

**Comment by borisfom** [comment]
Fixed.
