### ISSUE TITLE
torch.load fails to load "nan" floats in ascii mode

### ISSUE THREAD

**Issue by Wesmania** [soumith/torch-android#83]
torch.load uses e.g. THDiskFile to load objects from file, this in turn uses fscanf to load the file in ascii mode. Torch saves NaN as string "nan", but in my situation (emulator, NDK 22, armeabi-v7a) the following snippet:

sscanf("nan", "%g", buf)

returns 0 (i.e. no float was found). The loading routine promptly falls over having expected to read an NaN.

**Comment by borisfom** [comment]
This is inherent issue (or perhaps a feature) of sscanf. Not to be fixed here.
