### ISSUE TITLE
Does torch-android have fp16 support?

### ISSUE THREAD

**Issue by sixsamuraisoldier** [soumith/torch-android#84]
Only for weight quantization, not necessarily for computation. 

Thanks in advance.

**Comment by borisfom** [comment]
It has the same support as usual Torch (CUDA only for the moment). I am working on adding CPU FP16, ideally with native support on ARM.

**Comment by sixsamuraisoldier** [comment]
Awesome, CUDA will work great! Has it been tested on the NVIDIA Shield Tegra K1 Tablet?
Thanks for the quick response btw :)
