### ISSUE TITLE
Install failure despite CUDA being installed

### ISSUE THREAD

**Issue by sixsamuraisoldier** [soumith/torch-android#85]
Hi there, I'm getting an error even though I have CUDA installed (nvcc --version gives CUDA 8.0)

Found CUDA on your machine. Installing CMake 3.6 modules to get up-to-date FindCUDA
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sixsamuraisoldier/torch-android/torch-android/distro/cmake/3.6/build
Install the project...
-- Install configuration: ""
-- Installing: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA.cmake
-- Installing: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA/run_nvcc.cmake
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA/parse_cubin.cmake
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA/make2cmake.cmake
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake
FindCuda bits of CMake 3.6 installed
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build
 -------------- Configuring DONE ---------------
/usr/bin/cmake -H/home/sixsamuraisoldier/torch-android/torch-android/external/libpng -B/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/depend
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
cd /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/png16.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/png16.dir/build.make CMakeFiles/png16.dir/build
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/png16.dir/build'.
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
[ 45%] Built target png16
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/depend
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
cd /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/png16_static.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/png16_static.dir/build.make CMakeFiles/png16_static.dir/build
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/png16_static.dir/build'.
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles  18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
[ 91%] Built target png16_static
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/depend
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
cd /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/pngstest.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/pngstest.dir/build.make CMakeFiles/pngstest.dir/build
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/pngstest.dir/build'.
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles  35
[ 94%] Built target pngstest
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/depend
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
cd /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/pngtest.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/pngtest.dir/build.make CMakeFiles/pngtest.dir/build
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/pngtest.dir/build'.
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles  36
[ 97%] Built target pngtest
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/depend
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
cd /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles/pngvalid.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make -f CMakeFiles/pngvalid.dir/build.make CMakeFiles/pngvalid.dir/build
make[2]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[2]: Nothing to be done for `CMakeFiles/pngvalid.dir/build'.
make[2]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_report /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles  37
[100%] Built target pngvalid
make[1]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
/usr/bin/cmake -E cmake_progress_start /home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build/CMakeFiles 0
make -f CMakeFiles/Makefile2 preinstall
make[1]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
make[1]: Nothing to be done for `preinstall'.
make[1]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/external/libpng/build'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng16.so.16.20.0
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng16.so.16
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng16.so
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng16.a
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng.so
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng.a
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/png.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/pngconf.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/pnglibconf.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/libpng16/png.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/libpng16/pngconf.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/include/libpng16/pnglibconf.h
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/bin/libpng-config
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/man/man3/libpng.3
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/man/man3/libpngpf.3
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/share/man/man5/png.5
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/pkgconfig/libpng.pc
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/bin/libpng-config
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/pkgconfig/libpng16.pc
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng/libpng16.cmake
-- Installing: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/libpng/libpng16-noconfig.cmake
libpng installed
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[1]: Entering directory `/home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
DYNLINK   libluajit.so
/home/sixsamuraisoldier/NVPACK/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: unrecognized option '--fix-cortex-a8'
/home/sixsamuraisoldier/NVPACK/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
make[1]: *** [libluajit.so] Error 1
make[1]: Leaving directory `/home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
make: *** [default] Error 2
Done installing Lua
-- LuaJIT Target: arm64
-- LuaJIT target arm64
-- Using system lua for generating dynasm via: /home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua
-- Executing command: /home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/host/minilua /home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/dynasm/dynasm.lua -D;P64;-D;FFI;-D;DUALNUM;-D;FPU;-D;HFABI -o /home/sixsamuraisoldier/torch-android/torch-android/build/distro/exe/luajit-rocks/luajit-2.1/buildvm_arch.h /home/sixsamuraisoldier/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src/vm_arm64.dasc
-- LUA_INCDIR: /home/sixsamuraisoldier/torch-android/torch-android/install/include
-- LUA_LIBDIR: /home/sixsamuraisoldier/torch-android/torch-android/install/lib
-- LUA_BINDIR: /home/sixsamuraisoldier/torch-android/torch-android/install/bin
-- LUALIB: /home/sixsamuraisoldier/torch-android/torch-android/install/libs/arm64-v8a/libluajit.so
-- LUADIR: /home/sixsamuraisoldier/torch-android/torch-android/install/share/lua/5.1/
-- LIBDIR: /home/sixsamuraisoldier/torch-android/torch-android/install/lib/lua/5.1/
-- LUA_BINDIR: /home/sixsamuraisoldier/torch-android/torch-android/install/bin
-- SCRIPTS_DIR: /home/sixsamuraisoldier/torch-android/torch-android/install/bin
-- Compiling with OpenMP support
-- Compiling with OpenMP support
-- No OMAP3 processor on this on this machine.
-- No OMAP4 processor on this on this machine.
-- Neon found with compiler flag : -mfpu=neon -D__NEON__
-- Atomics: using pthread
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
-- Checking for [blas]
--   Library blas: BLAS_blas_LIBRARY-NOTFOUND
-- Cannot find a library with BLAS API. Not using BLAS.
-- LAPACK requires BLAS
-- Cannot find a library with LAPACK API. Not using LAPACK.
-- C inline seems not supported
-- Warning: __thread is not supported, generating thread-unsafe code
-- Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- Compiling with OpenMP support
WARNING: Could not find JPEG libraries, JPEG wrapper will not be installed
-- Compiling with OpenMP support
-- OpenMP Found with compiler flag : -fopenmp
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_INCLUDE_DIRS
  CUDA_CUDART_LIBRARY) (found suitable version "8.0", minimum required is
  "6.5")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  install/share/cmake/torch/FindCUDA.cmake:1009 (find_package_handle_standard_args)
  distro/extra/cutorch/CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/sixsamuraisoldier/torch-android/torch-android/build/CMakeFiles/CMakeOutput.log".
See also "/home/sixsamuraisoldier/torch-android/torch-android/build/CMakeFiles/CMakeError.log".
 -------------- Configuring DONE ---------------
make: *** No rule to make target `install'.  Stop.

**Comment by paramsen** [comment]
`Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_INCLUDE_DIRS
CUDA_CUDART_LIBRARY)` Are these env vars defined? The manual CUDA installation on Ubuntu finishes with prompting the user to add these variables along with adding CUDA to the PATH env var. It can easily be missed when installing CUDA.

**Comment by sixsamuraisoldier** [comment]
Yes, they are defined, nvcc works fine.

**Comment by paramsen** [comment]
Ok then, note that nvcc works fine without `CUDA_TOOLKIT_ROOT_DIR CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY` as long as CUDA is in your path. I missed adding these vars and got the exact same output, with nvcc working.

**Comment by sixsamuraisoldier** [comment]
Where did you set those env variables paths to?

**Comment by culurciello** [comment]
use this instead of this repo: https://github.com/e-lab/apps-android

**Comment by sixsamuraisoldier** [comment]
@culurciello Oh yeah, that's the demo that uses this, good idea@ Thanks :)

**Comment by BrianOn99** [comment]
@culurciello May I know what is the demo app detecting?  It keeps 0.0% on my phone.

**Comment by culurciello** [comment]
you will need a trained neural network from torch to use this

**Comment by sixsamuraisoldier** [comment]
@BrianOn99 You can grab a pre-trained network and use it.

**Comment by borisfom** [comment]
Please pull and try again.

**Comment by sixsamuraisoldier** [comment]
@borisfom For torch-android?

**Comment by borisfom** [comment]
@sixsamuraisoldier: yes. (I have deleted foreign app thread)

**Comment by sixsamuraisoldier** [comment]
@borisfom awesome, I'll try it!

**Comment by sixsamuraisoldier** [comment]
@borisfom same error

**Comment by borisfom** [comment]
@sixsamuraisoldier Please read README: you need to have CUDA for Android installed and have nvcc from CodeWorks in the path, not your host compiler.
which nvcc
~/NVPACK/cuda-7.0/bin/nvcc
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Wed_Jul_29_05:02:50_CDT_2015
Cuda compilation tools, release 7.0, V7.0.59

**Comment by sixsamuraisoldier** [comment]
My NVPACK install doesn't have a /cuda-7.0 even though I got the 1R5 version.

**Comment by borisfom** [comment]
@sixsamuraisoldier : please read README again, it explains where to get it.

**Comment by sixsamuraisoldier** [comment]
Oh I see, sorry for bothering you. Thank you! I will close this issue.

**Comment by culurciello** [comment]
Also take a look at this: https://github.com/e-lab/apps-android it may be easier to use in some cases

**Comment by borisfom** [comment]
The vm build is now fixed for both V7 and V8. Be sure to read README for extra gcc packages needed to build 32  code on 64-bit system.
