### ISSUE TITLE
Minimum Android sdk version

### ISSUE THREAD

**Issue by paramsen** [soumith/torch-android#97]
There's no information about which minimum Android sdk version `torch-android` supports. [Default is 21][1], is that because it's the minimum supported sdk as of today?

[1]: https://github.com/soumith/torch-android/blob/master/build.sh#L5

**Comment by shijie-nv** [comment]
for v7n 
NDKABI=9 is enough
for 64bits V8
NDKABI=21 (android 6.0 started to support 64bits)

**Comment by shijie-nv** [comment]
torch for android does not depend on any STL
so you can modify the build.sh to eliminate the gnustl_shared.so
```
< NDKABI=9
---
> NDKABI=21
13c13
< WITH_CUDA=${WITH_CUDA:-"OFF"}
---
> WITH_CUDA=${WITH_CUDA:-"ON"}
102c102
<     -DANDROID_NATIVE_API_LEVEL="${NDKABI}" -DANDROID_STL=none\
---
>     -DANDROID_NATIVE_API_LEVEL="${NDKABI}" -DANDROID_STL=gnustl_shared\
```

**Comment by paramsen** [comment]
I built `torch-android` for api 16 which worked good for my app that has minSdk 16. @shijie001 your answer gives context to why it's set to 21 per default in this repo, I never though of which minimum api V8 supports! 

In case anyone wonders, there are conflicts if you simply build for API 21 and try to include the built binaries in an app with minSdk < 21. This is because between api 19 and 21 some headers were converted to inline in the Android source, so in order to support minSdk < 21 you should build torch for that target api (it's backwards compatible tho so torch built for api 16 works on 16+). Some of the lua binaries depend on the inline headers.
